apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-python-job
spec:
  schedule: "0 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-python-container
            image: python:3.9  # Use the appropriate Python image
            command: ["python", "/src/root/main.py"]
            env:
            - name: GMAIL_SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: gmail_sender_email
            - name: GMAIL_RECEIVER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: gmail_receiver_email
            - name: GMAIL_RECEIVER_EMAIL_2
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: gmail_receiver_email_2
            - name: GMAIL_RECEIVER_EMAIL_3
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: gmail_receiver_email_3
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: gmail_app_password
            - name: HAFELE_ONLINE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: hafele_online_username
            - name: HAFELE_ONLINE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-credentials
                  key: hafele_online_password
          restartPolicy: OnFailure
